@startuml


actor User as "EdgeNode\nAdmin"
participant SSP as "Enrollment\nUI"
participant Keycloak
participant Vault
participant EdgeNode

== Authentication == 
User -> SSP : login
SSP -> Keycloak : oidc login
note left
The login process may be also done directly
via Vault using other mechanisms, e.g. TOTP
or Vault managed user/passwords etc.
end note
return JWT

== Initialization ==
User -> SSP : create edge node
SSP -> Vault : create entity and entity alias
SSP -> Vault : generate token
return token

SSP --> User : token
note left 
This script may be used exactly once, 
as the contained token 
expires after first usage.
end note
User -> EdgeNode : configure
note left: provisioning of token and configuration

== Communication ==

alt no valid client certificate available
    EdgeNode -> Vault : authenticate(token)
    return certificate
    EdgeNode -> EdgeNode : storeToFilesystem(certificate)
    EdgeNode -> EdgeNode : re-establish connections
end
EdgeNode -> CloudCore : establish communication(client certificate)




@enduml
